### ISSUE TITLE
Rev4 connectors

### ISSUE THREAD

**Issue by E-Ruhl** [oresat/oresat-adcs-hardware#9]
Looking into different styles of connectors, I found this one:

data sheet:
https://www.hirose.com/product/document?clcode=CL0580-1251-5-99&productname=FH34SRJ-10S-0.5SH(99)&series=FH34SRJ&documenttype=Catalog&lang=en&documentid=D31646_en

digikey:
https://www.digikey.com/product-detail/en/hirose-electric-co-ltd/FH34SRJ-14S-0.5SH-99/H124721CT-ND/5156024

In terms of cable, this looks pretty good:

https://www.digikey.com/product-detail/en/molex/0151660141/WM11330-ND/3281022

but we might have to peel off the shielding on one end to get the double contact from the port, also not really sure what length to get since I don't have anything for an oresat card yet. I should probably talk to Patrick about getting geometry for the board.

**Comment by andrewgreenberg** [comment]
Fixed in upcoming Rev 7.
